-- Run once in the Supabase SQL editor before deploying the desktop clients.
-- These functions keep destructive replacements and duplicate-safe imports in
-- a single database transaction. This deployment uses a shared office client:
-- one of three operator names is selected in the desktop app for audit records,
-- while the Supabase publishable key supplies the database role.

create table if not exists public.app_authorized_users (
    user_id uuid primary key references auth.users(id) on delete cascade,
    display_name text not null,
    active boolean not null default true,
    created_at timestamptz not null default now()
);

alter table public.app_authorized_users enable row level security;
revoke all on public.app_authorized_users from anon, authenticated;

create or replace function public.is_authorized_operator()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select auth.role() in ('anon', 'authenticated', 'service_role');
$$;

create or replace function public.current_operator_name()
returns text
language sql
stable
security definer
set search_path = public
as $$
    select display_name
    from public.app_authorized_users
    where user_id = auth.uid()
      and active
    limit 1;
$$;

revoke all on function public.is_authorized_operator() from public;
revoke all on function public.current_operator_name() from public, anon;
grant execute on function public.is_authorized_operator() to anon, authenticated;
grant execute on function public.current_operator_name() to authenticated;

create table if not exists public.app_audit_log (
    id bigint generated by default as identity primary key,
    operator text not null,
    action text not null,
    entity_type text not null,
    entity_id text,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.app_audit_log enable row level security;
revoke all on public.app_audit_log from anon, authenticated;

alter table public.students enable row level security;
alter table public.expenses enable row level security;
alter table public.budgets enable row level security;
alter table public.coordinators enable row level security;
alter table public.donor_students enable row level security;
alter table public.student_movements enable row level security;
alter table public.app_updates enable row level security;

drop policy if exists "authorized operators manage students" on public.students;
create policy "authorized operators manage students"
    on public.students for all to anon, authenticated
    using (public.is_authorized_operator())
    with check (public.is_authorized_operator());

drop policy if exists "authorized operators manage expenses" on public.expenses;
create policy "authorized operators manage expenses"
    on public.expenses for all to anon, authenticated
    using (public.is_authorized_operator())
    with check (public.is_authorized_operator());

drop policy if exists "authorized operators manage budgets" on public.budgets;
create policy "authorized operators manage budgets"
    on public.budgets for all to anon, authenticated
    using (public.is_authorized_operator())
    with check (public.is_authorized_operator());

drop policy if exists "authorized operators manage coordinators" on public.coordinators;
create policy "authorized operators manage coordinators"
    on public.coordinators for all to anon, authenticated
    using (public.is_authorized_operator())
    with check (public.is_authorized_operator());

drop policy if exists "authorized operators manage donor students" on public.donor_students;
create policy "authorized operators manage donor students"
    on public.donor_students for all to anon, authenticated
    using (public.is_authorized_operator())
    with check (public.is_authorized_operator());

drop policy if exists "authorized operators manage student movements" on public.student_movements;
create policy "authorized operators manage student movements"
    on public.student_movements for all to anon, authenticated
    using (public.is_authorized_operator())
    with check (public.is_authorized_operator());

drop policy if exists "authorized operators read updates" on public.app_updates;
create policy "authorized operators read updates"
    on public.app_updates for select to anon, authenticated
    using (public.is_authorized_operator());

drop policy if exists "authorized operators append audit entries" on public.app_audit_log;
create policy "authorized operators append audit entries"
    on public.app_audit_log for insert to anon, authenticated
    with check (public.is_authorized_operator());

drop policy if exists "authorized operators read audit entries" on public.app_audit_log;
create policy "authorized operators read audit entries"
    on public.app_audit_log for select to anon, authenticated
    using (public.is_authorized_operator());

grant select, insert, update, delete on
    public.students,
    public.expenses,
    public.budgets,
    public.coordinators,
    public.donor_students,
    public.student_movements
to anon, authenticated;
grant select on public.app_updates to anon, authenticated;
grant select, insert on public.app_audit_log to anon, authenticated;
grant usage, select on sequence public.app_audit_log_id_seq to anon, authenticated;

create unique index if not exists budgets_student_school_year_key
    on public.budgets (student_id, school_year);

alter table public.donor_students
    add column if not exists student_id uuid references public.students(id) on delete cascade;

alter table public.student_movements
    add column if not exists student_id uuid references public.students(id) on delete cascade;

do $$
begin
    -- Legacy installs may still have name columns marked NOT NULL. The desktop
    -- importer now writes canonical student_id links, so those text columns must
    -- be optional if they still exist.
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'donor_students'
          and column_name = 'last_name'
    ) then
        alter table public.donor_students alter column last_name drop not null;
    end if;

    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'donor_students'
          and column_name = 'first_name'
    ) then
        alter table public.donor_students alter column first_name drop not null;
    end if;

    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'student_movements'
          and column_name = 'last_name'
    ) then
        alter table public.student_movements alter column last_name drop not null;
    end if;

    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'student_movements'
          and column_name = 'first_name'
    ) then
        alter table public.student_movements alter column first_name drop not null;
    end if;
end;
$$;

create index if not exists donor_students_student_id_idx
    on public.donor_students (student_id);

create index if not exists student_movements_student_id_idx
    on public.student_movements (student_id);

create or replace function public.replace_coordinators_transactional(payload jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    inserted_count integer;
begin
    if not public.is_authorized_operator() then
        raise exception 'SSM operator authorization required' using errcode = '42501';
    end if;
    lock table public.coordinators in exclusive mode;
    delete from public.coordinators where true;
    insert into public.coordinators (
        location, contact_person, email, contact_no, fb_page, remarks
    )
    select location, contact_person, email, contact_no, fb_page, remarks
    from jsonb_to_recordset(payload) as record(
        location text,
        contact_person text,
        email text,
        contact_no text,
        fb_page text,
        remarks text
    );
    get diagnostics inserted_count = row_count;
    return inserted_count;
end;
$$;

create or replace function public.replace_donor_students_transactional(
    target_school_year text,
    payload jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    inserted_count integer;
begin
    if not public.is_authorized_operator() then
        raise exception 'SSM operator authorization required' using errcode = '42501';
    end if;
    lock table public.donor_students in exclusive mode;
    delete from public.donor_students where school_year = target_school_year;
    insert into public.donor_students (
        school_year, donor_name, student_id,
        location, level, sponsor, remarks
    )
    select school_year, donor_name, student_id,
           location, level, sponsor, remarks
    from jsonb_to_recordset(payload) as record(
        school_year text,
        donor_name text,
        student_id uuid,
        location text,
        level text,
        sponsor text,
        remarks text
    );
    get diagnostics inserted_count = row_count;
    return inserted_count;
end;
$$;

create or replace function public.replace_student_movements_transactional(payload jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    inserted_count integer;
begin
    if not public.is_authorized_operator() then
        raise exception 'SSM operator authorization required' using errcode = '42501';
    end if;
    lock table public.student_movements in exclusive mode;
    delete from public.student_movements where true;
    insert into public.student_movements (
        category, student_id, location, level, remarks
    )
    select category, student_id, location, level, remarks
    from jsonb_to_recordset(payload) as record(
        category text,
        student_id uuid,
        location text,
        level text,
        remarks text
    );
    get diagnostics inserted_count = row_count;
    return inserted_count;
end;
$$;

create or replace function public.import_students_transactional(payload jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    processed integer;
begin
    if not public.is_authorized_operator() then
        raise exception 'SSM operator authorization required' using errcode = '42501';
    end if;
    if jsonb_array_length(payload) = 0 then
        return 0;
    end if;

    -- Serialize imports so two desktop clients cannot create conflicting rosters.
    perform pg_advisory_xact_lock(hashtext('ssm-student-import'));
    lock table public.students in exclusive mode;

    create temporary table import_student_payload on commit drop as
    select
        row_number() over () as import_row,
        last_name,
        first_name,
        gender,
        grade,
        address,
        city,
        area,
        nullif(trim(birthday), '') as birthday,
        sponsor,
        contact,
        school,
        parents,
        course,
        remarks,
        coalesce(nullif(status, ''), 'Active') as status
    from jsonb_to_recordset(payload) as record(
        last_name text,
        first_name text,
        gender text,
        grade text,
        address text,
        city text,
        area text,
        birthday text,
        sponsor text,
        contact text,
        school text,
        parents text,
        course text,
        remarks text,
        status text
    );

    create temporary table import_student_keep on commit drop as
    select p.import_row, matched.id
    from import_student_payload p
    join lateral (
        select s.id
        from public.students s
        where lower(trim(s.last_name)) = lower(trim(p.last_name))
          and lower(trim(s.first_name)) = lower(trim(p.first_name))
        order by (
            nullif(trim(s.birthday), '') is not distinct from p.birthday
        ) desc, s.id
        limit 1
    ) matched on true;

    update public.students s
    set gender = p.gender,
        grade = p.grade,
        address = p.address,
        city = p.city,
        area = p.area,
        birthday = p.birthday,
        sponsor = p.sponsor,
        contact = p.contact,
        school = p.school,
        parents = p.parents,
        course = p.course,
        remarks = p.remarks,
        status = p.status
    from import_student_keep k
    join import_student_payload p on p.import_row = k.import_row
    where s.id = k.id;

    insert into public.students (
        last_name, first_name, gender, grade, address, city, area,
        birthday, sponsor, contact, school, parents, course, remarks, status
    )
    select
        p.last_name, p.first_name, p.gender, p.grade, p.address, p.city, p.area,
        p.birthday, p.sponsor, p.contact, p.school, p.parents, p.course,
        p.remarks, p.status
    from import_student_payload p
    where not exists (
        select 1
        from import_student_keep k
        where k.import_row = p.import_row
    );

    select count(*) into processed from import_student_payload;
    return processed;
end;
$$;

revoke all on function public.replace_coordinators_transactional(jsonb) from public;
revoke all on function public.replace_donor_students_transactional(text, jsonb) from public;
revoke all on function public.replace_student_movements_transactional(jsonb) from public;
revoke all on function public.import_students_transactional(jsonb) from public;
grant execute on function public.replace_coordinators_transactional(jsonb) to anon, authenticated, service_role;
grant execute on function public.replace_donor_students_transactional(text, jsonb) to anon, authenticated, service_role;
grant execute on function public.replace_student_movements_transactional(jsonb) to anon, authenticated, service_role;
grant execute on function public.import_students_transactional(jsonb) to anon, authenticated, service_role;

-- Supabase Storage policies for student photos. The bucket itself must already
-- exist and remain private.
drop policy if exists "authorized operators read student photos" on storage.objects;
create policy "authorized operators read student photos"
    on storage.objects for select to anon, authenticated
    using (
        bucket_id = 'student-photos'
        and public.is_authorized_operator()
    );

drop policy if exists "authorized operators add student photos" on storage.objects;
create policy "authorized operators add student photos"
    on storage.objects for insert to anon, authenticated
    with check (
        bucket_id = 'student-photos'
        and public.is_authorized_operator()
    );

drop policy if exists "authorized operators update student photos" on storage.objects;
create policy "authorized operators update student photos"
    on storage.objects for update to anon, authenticated
    using (
        bucket_id = 'student-photos'
        and public.is_authorized_operator()
    )
    with check (
        bucket_id = 'student-photos'
        and public.is_authorized_operator()
    );

drop policy if exists "authorized operators delete student photos" on storage.objects;
create policy "authorized operators delete student photos"
    on storage.objects for delete to anon, authenticated
    using (
        bucket_id = 'student-photos'
        and public.is_authorized_operator()
    );
