-- Run once in the Supabase SQL editor before deploying the desktop clients.
-- These functions keep destructive replacements and duplicate-safe imports in
-- a single database transaction. Desktop clients call them with the service key.

create table if not exists public.app_audit_log (
    id bigint generated by default as identity primary key,
    operator text not null,
    action text not null,
    entity_type text not null,
    entity_id text,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.app_audit_log enable row level security;
revoke all on public.app_audit_log from anon, authenticated;

create unique index if not exists budgets_student_school_year_key
    on public.budgets (student_id, school_year);

create or replace function public.replace_coordinators_transactional(payload jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    inserted_count integer;
begin
    lock table public.coordinators in exclusive mode;
    delete from public.coordinators;
    insert into public.coordinators (
        location, contact_person, email, contact_no, fb_page, remarks
    )
    select location, contact_person, email, contact_no, fb_page, remarks
    from jsonb_to_recordset(payload) as record(
        location text,
        contact_person text,
        email text,
        contact_no text,
        fb_page text,
        remarks text
    );
    get diagnostics inserted_count = row_count;
    return inserted_count;
end;
$$;

create or replace function public.replace_donor_students_transactional(
    target_school_year text,
    payload jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    inserted_count integer;
begin
    lock table public.donor_students in exclusive mode;
    delete from public.donor_students where school_year = target_school_year;
    insert into public.donor_students (
        school_year, donor_name, last_name, first_name,
        location, level, sponsor, remarks
    )
    select school_year, donor_name, last_name, first_name,
           location, level, sponsor, remarks
    from jsonb_to_recordset(payload) as record(
        school_year text,
        donor_name text,
        last_name text,
        first_name text,
        location text,
        level text,
        sponsor text,
        remarks text
    );
    get diagnostics inserted_count = row_count;
    return inserted_count;
end;
$$;

create or replace function public.replace_student_movements_transactional(payload jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    inserted_count integer;
begin
    lock table public.student_movements in exclusive mode;
    delete from public.student_movements;
    insert into public.student_movements (
        category, last_name, first_name, location, level, remarks
    )
    select category, last_name, first_name, location, level, remarks
    from jsonb_to_recordset(payload) as record(
        category text,
        last_name text,
        first_name text,
        location text,
        level text,
        remarks text
    );
    get diagnostics inserted_count = row_count;
    return inserted_count;
end;
$$;

create or replace function public.import_students_transactional(payload jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    item jsonb;
    affected integer;
    processed integer := 0;
    birthday_value date;
begin
    -- Serialize imports so two desktop clients cannot create the same student.
    perform pg_advisory_xact_lock(hashtext('ssm-student-import'));

    for item in select value from jsonb_array_elements(payload)
    loop
        birthday_value := nullif(item ->> 'birthday', '')::date;
        update public.students
        set gender = item ->> 'gender',
            grade = item ->> 'grade',
            address = item ->> 'address',
            city = item ->> 'city',
            area = item ->> 'area',
            sponsor = item ->> 'sponsor',
            contact = item ->> 'contact',
            school = item ->> 'school',
            parents = item ->> 'parents',
            course = item ->> 'course',
            remarks = item ->> 'remarks',
            status = coalesce(nullif(item ->> 'status', ''), 'Active')
        where lower(trim(last_name)) = lower(trim(item ->> 'last_name'))
          and lower(trim(first_name)) = lower(trim(item ->> 'first_name'))
          and birthday is not distinct from birthday_value;
        get diagnostics affected = row_count;

        if affected = 0 then
            insert into public.students (
                last_name, first_name, gender, grade, address, city, area,
                birthday, sponsor, contact, school, parents, course, remarks, status
            ) values (
                item ->> 'last_name', item ->> 'first_name', item ->> 'gender',
                item ->> 'grade', item ->> 'address', item ->> 'city', item ->> 'area',
                birthday_value, item ->> 'sponsor', item ->> 'contact', item ->> 'school',
                item ->> 'parents', item ->> 'course', item ->> 'remarks',
                coalesce(nullif(item ->> 'status', ''), 'Active')
            );
        end if;
        processed := processed + 1;
    end loop;
    return processed;
end;
$$;

revoke all on function public.replace_coordinators_transactional(jsonb) from public, anon, authenticated;
revoke all on function public.replace_donor_students_transactional(text, jsonb) from public, anon, authenticated;
revoke all on function public.replace_student_movements_transactional(jsonb) from public, anon, authenticated;
revoke all on function public.import_students_transactional(jsonb) from public, anon, authenticated;
grant execute on function public.replace_coordinators_transactional(jsonb) to service_role;
grant execute on function public.replace_donor_students_transactional(text, jsonb) to service_role;
grant execute on function public.replace_student_movements_transactional(jsonb) to service_role;
grant execute on function public.import_students_transactional(jsonb) to service_role;
